### PR TITLE
Slug dot into slash

### PR DESCRIPTION
**Pull request by lluiscampos**
Grav translate it this way for the reference-able headers

### CODE REVIEW

**Comment by lluiscampos** [comment]
@oleorhagen This (or a similar fix) is required for https://github.com/mendersoftware/mender-docs/pull/1812

**Comment by oleorhagen** [comment]
> @oleorhagen This (or a similar fix) is required for [mendersoftware/mender-docs#1812](https://github.com/mendersoftware/mender-docs/pull/1812)

Understood, but it's been a while. Have you done this, or do I need to follow-up with something here?

**Comment by lluiscampos** [comment]
> > @oleorhagen This (or a similar fix) is required for [mendersoftware/mender-docs#1812](https://github.com/mendersoftware/mender-docs/pull/1812)
> 
> Understood, but it's been a while. Have you done this, or do I need to follow-up with something here?

You need to approve and merge this one :smile: Then I will take take care of re-submitting the `mender-docs` PR

**Comment by oleorhagen** [comment]
> > > @oleorhagen This (or a similar fix) is required for [mendersoftware/mender-docs#1812](https://github.com/mendersoftware/mender-docs/pull/1812)
> > 
> > 
> > Understood, but it's been a while. Have you done this, or do I need to follow-up with something here?
> 
> You need to approve and merge this one smile Then I will take take care of re-submitting the `mender-docs` PR

Should this project be migrated to `mendersoftware` while we are at it? :thinking:

**Comment by lluiscampos** [comment]
> Should this project be migrated to `mendersoftware` while we are at it? thinking

We could. But we also need to move [remark-validate-links](https://github.com/oleorhagen/remark-validate-links/) and update then the `package.json` in mender-docs. I would say it is nice to do, not a requirement.

**Pull request merged**
